config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :carts
  get 'store' => 'store#index'
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get 'home' => 'static_pages#home'
  get 'contact' =>'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'signup' => 'users#new'
  get 'new_orders_url' => 'orders#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'products/update'
  
  get 'new_orders_url' => 'orders#new'
  post 'orders_url' => 'orders#create'
  post 'line_items_url' => 'link_items#create'
  
  resources :users
  resources :products do
    get :who_bought, on: :member
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  include CurrentCart
  before_action :set_cart
  
  def index
    @products = Product.order(:title)
  end
end

app/helpers/store_helper.rb
module StoreHelper

  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
  
end

app/views/store/index.html.erb
<% provide(:title, "Shop") %>
<%= render 'layouts/header' %>
<p id="notice"><%= notice %></p>  
  <nav>
    <ul class="nav-list">
      <li class="home"><%= link_to "Home", home_path %></li>
      <li class="shop selected"><%= link_to "Shop", store_path %></li>
      <li class="about_us"><%= link_to "About", about_path %></li>
      <li class="contact"><%= link_to "Contact", contact_path %></li>
              <li class="navtxt"id='cart-button'>
              <%= link_to @cart do %>
                <%= image_tag("cart_small.png") %>
              <% end %>
        </li>
    </ul>
  </nav>
  



<h1>Store</h1>
  <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
        <%= render @cart %>
  <% end %>
  
<% @products.each do |product| %>
  <div class="entry">
    <%= image_tag(product.image_url) %>
    <h3><%= product.title %></h3>
    <%= sanitize(product.description) %>
    <div class="price_line">
      <span class="price"><%= number_to_currency(product.price, :unit => "€") %></span>
        <%= button_to 'Add to Cart', line_items_path(product_id: product),
          remote: true %>
    </div>
  </div>
<% end %>